### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by PoSayDone** [Paul-Houser/StartTree#10]
How to make the background of this home page transparent in firefox?

**Comment by Paul-Houser** [comment]
The transparency in the screenshot is not a feature of StartTree, there's just a compositor running on the system that the screenshot was taken on. I use Picom, but there are other options.

**Comment by PoSayDone** [comment]
I understand that is made by using compositor, but which css code I need to use to make the new tab background transparent, or you made the whole ff window transprent by picom?

**Comment by Paul-Houser** [comment]
yea its just the entire window being made transparent with picom, no special css

**Comment by PoSayDone** [comment]
Okay, thanks for your answer

**Comment by Paul-Houser** [comment]
If you're interested, this is the command that will launch picom using the nice blur:
`picom --config=/path/to/config/picom.conf --experimental-backends --backend glx --blur-method dual_kawse -b`
and I think you need opacity enabled in your picom.conf. Also, the `-b` starts picom as a daemon, so leave that off if you don't want that.

**Comment by PoSayDone** [comment]
> If you're interested, this is the command that will launch picom using the nice blur:
> `picom --config=/path/to/config/picom.conf --experimental-backends --backend glx --blur-method dual_kawse -b`
> and I think you need opacity enabled in your picom.conf. Also, the `-b` starts picom as a daemon, so leave that off if you don't want that.

Thanks a lot, but I use ibhagwan picom, so I know about this. I'm just trying to find the way to make firefox tab background transparent. I don't really know much about userChrome, thought you know.
